name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  verify:
    uses: Mad-Pixels/github-workflows/.github/workflows/github-check-tag.yml@main

  build:
    uses: Mad-Pixels/github-workflows/.github/workflows/node-build.yml@main
    with:
      working-directory: ./app
      node-version: '20'

  apply:
    uses: Mad-Pixels/github-workflows/.github/workflows/aws-terraform.yml@main
    with:
      terraform_command: apply
      actions_verions: "0.0.1"
      terraform_workspace: "main"
      working_directory: "terraform/provisioners/infra/"
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      TF_BACKEND_JSON: ${{ secrets.TF_BACKEND_JSON }}
      TF_VARS_JSON: ${{ secrets.TF_VARS_JSON }}

  discover:
    needs: [build]
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist_files

  upload:
    needs: [discover]
    uses: Mad-Pixels/github-workflows/.github/workflows/aws-s3-sync.yml@main
    with:
      artifacts: "dist"
      working_directory: "dist_files"
      actions_verions: "0.0.1"
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      BUCKET_DESTINATION: ${{ secrets.DOCS_BUCKET }}