name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  # verify:
  #   uses: Mad-Pixels/github-workflows/.github/workflows/github-check-tag.yml@main

  build:
    uses: Mad-Pixels/github-workflows/.github/workflows/node-build.yml@node
    with:
      working-directory: ./app
      node-version: '20'

  discover:
    needs: [build]
    runs-on: ubuntu-24.04
    steps:
      - name: Create working directory
        run: mkdir -p dist_files

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: vue-dist
          path: dist_files

      - name: Upload working directory
        uses: actions/upload-artifact@v4
        with:
          name: files-to-sync
          path: dist_files
          retention-days: 1

  upload:
    needs: [discover]
    uses: Mad-Pixels/github-workflows/.github/workflows/aws-s3-sync.yml@node
    with:
      working_directory: "dist_files"
      actions_verions: "0.0.1"
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      BUCKET_DESTINATION: ${{ secrets.DOCS_BUCKET }}