name: Release

on:
  push:
    branches-ignore:
      - main
    # tags:
    #   - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  infra:
    uses: Mad-Pixels/github-workflows/.github/workflows/aws-terraform.yml@main
    with:
      terraform_command: plan
      actions_verions: "0.0.1"
      working_directory: "terraform/provisioners/infra/"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      # TERRAFORM_BACKEND_REGION: ${{ secrets.AWS_BACKEND_REGION }}
      # TERRAFORM_BACKEND_BUCKET: ${{ secrets.AWS_BACKEND_BUCKET }}
      # TERRAFORM_BACKEND_KEY: ${{ secrets.AWS_BACKEND_KEY }}
      #TF_VARS_JSON: ${{ secrets.TF_VARS_JSON }}
    
  # service:
  #   uses: Mad-Pixels/github-workflows/.github/workflows/aws-terraform.yml@main
  #   with:
  #     terraform_command: apply
  #     working_directory: "terraform/provisioners/service/" 
  #   secrets:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  #     TERRAFORM_BACKEND_REGION: ${{ secrets.AWS_BACKEND_REGION }}
  #     TERRAFORM_BACKEND_BUCKET: ${{ secrets.AWS_BACKEND_BUCKET }}
  #     TERRAFORM_BACKEND_KEY: ${{ secrets.AWS_BACKEND_KEY }}
  #     TF_VARS_JSON: ${{ secrets.TF_VARS_JSON }}
